### ISSUE TITLE
BSS logo update

### ISSUE THREAD

**Issue by ima-studio** [simonyiszk/schdesign-logotar#37]
A logótárban nem az általánosan elfogadott BSS logó szerepel, és mivel a rendezvényekhez (pl. Gólyakörte) innen szedik le a rendezők, szeretnénk, ha megfelelő lenne a kinézete. Az alábbi mappában megtalálható hozzá néhány fájl: https://drive.google.com/drive/u/1/folders/1KVUNoxjhqDLNx4Bv6bmiIv5R1ICf_0aU

**Comment by gergoradeczki** [comment]
@ima-studio nezd meg most a weboldalt: https://logotar.schdesign.hu

**Comment by ima-studio** [comment]
Köszi szépen, sok éves kívánság lett meg így :D
